GET http://localhost:5291/games

###
GET http://localhost:5291/games/4

###
POST http://localhost:5291/games
Content-Type: application/json

{
    "name" : "Street Fighter II",
    "genre" : "Fighting",
    "releaseDate" : "1991-02-01",
    "price" : 19.99,
    "imageUri" : "https://placehold.co/100"
}

###
PUT http://localhost:5291/games/4
Content-Type: application/json

{
    "name" : "Street Fighter II",
    "genre" : "Fighting",
    "releaseDate" : "1991-02-01",
    "price" : 19.99,
    "imageUri" : "https://placehold.co/100"
}

###
DELETE http://localhost:5291/games/1